# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.100.199.202"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.hostname = "database"
   
  #Must execute "vagrant plugin install vagrant-proxyconf" before "vagrant up"
  config.proxy.http = "http://10.110.8.42:8080"
  config.proxy.https = "http://10.110.8.42:8080"

  config.vm.provision "shell", inline: <<-SHELL
   sudo su
   apt-get upgrade
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
   apt-get update
   apt-get install -y docker-ce
 SHELL

 # config.vm.provision "docker"
  
end
