version: '2'

services:

  elasticsearch:
    container_name: elasticsearch
    build: ../elk/elasticsearch/
    volumes:
      - ../elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      the_box:
        ipv4_address: 172.15.0.2

  logstash:
    container_name: logstash
    build: ../elk/logstash/
    volumes:
      - ../elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      the_box:
        ipv4_address: 172.15.0.3
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build: ../elk/kibana/
    volumes:
      - ../elk/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      the_box:
        ipv4_address: 172.15.0.4
    depends_on:
      - elasticsearch

networks:
  the_box:
    ipam:
      driver: default
      config:
      - subnet: 172.15.0.0/24
        gateway: 172.15.0.1
