version: '2'
services:

  db:
    container_name: db
    ports:
      - 3306:3306
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'users' 
      MYSQL_USER: 'users'
      MYSQL_PASS: '123'
    volumes:
      - my-datavolume:/var/lib/mysql 
    networks:
      the_box:
        ipv4_address: 172.16.0.3
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  web:
    container_name: web
    ports:
      - 80:8081
    links:
      - sign_up_ms:sign_up_ms
      - get_client_ms:get_client_ms
      - delete_client_ms:delete_client_ms
      - update_client_ms:update_client_ms
    restart: always
    image: the_box_web
    networks:
      the_box:
        ipv4_address: 172.16.0.2
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  db_connection:
    container_name: db_connection
    ports:
      - 8082:8082
    links:
      - db:db
      - web:web
    environment:
      DATABASE_HOST: 'db'
    restart: always
    image: db_connection
    networks:
      the_box:
        ipv4_address: 172.16.0.4
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  sign_up_ms:
    container_name: sign_up_ms
    ports:
      - 8087:8087
    links:
      - mule:mule
    restart: always
    image: sign_up_ms
    networks:
      the_box:
        ipv4_address: 172.16.0.9
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  get_client_ms:
    container_name: get_client_ms
    ports:
      - 8084:8084
    links:
      - mule:mule
    restart: always
    image: get_client_ms
    networks:
      the_box:
        ipv4_address: 172.16.0.6
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  delete_client_ms:
    container_name: delete_client_ms
    ports:
      - 8085:8085
    links:
      - mule:mule
    restart: always
    image: delete_client_ms
    networks:
      the_box:
        ipv4_address: 172.16.0.7
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  update_client_ms:
    container_name: update_client_ms
    ports:
      - 8086:8086
    links:
      - mule:mule
    restart: always
    image: update_client_ms
    networks:
      the_box:
        ipv4_address: 172.16.0.8
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"
  
  mule:
    container_name: mule
    ports:
      - 8083:8083
    restart: always
    volumes:
      - /vagrant/mule/apps:/opt/mule/apps
      - /vagrant/mule/logs:/opt/mule/logs
    image: mule
    networks:
      the_box:
        ipv4_address: 172.16.0.5
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:5000"

volumes:
  my-datavolume:
networks:
  the_box:
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1