Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "docker-host"
  config.vm.provider "virtualbox" do |v|
		v.memory = 4096
       	v.cpus = 2
  end

  config.proxy.http     = "http://10.110.8.42:8080"
  config.proxy.https    = "http://10.110.8.42:8080"
  config.proxy.no_proxy = "localhost,127.0.0.1"

  config.vm.provision "docker"
  config.vm.network :forwarded_port, guest: 80, host: 8081, host_ip: "127.0.0.1"
  config.vm.define "environtment" do |server|
    server.vm.hostname = "monitoring"
    server.vm.network "private_network", ip: "10.110.0.210"
    server.vm.network "forwarded_port", guest: 5601, host: 5601     #KIBANA
    server.vm.network "forwarded_port", guest: 9200, host: 9200     #ELASTICSEARCH
    server.vm.network "forwarded_port", guest: 9300, host: 9300     #ELASTICSEARCH
    server.vm.network "forwarded_port", guest: 5000, host: 5000     #LOGSTASH
  end


end